site_name: FletX Framework
site_url: https://your-docs-url.com
repo_url: https://github.com/AllDotPy/FletX
repo_name: FletX

theme:
  name: material

  # LOGO AND FAVICON
  logo: assets/logo/fletx.png
  favicon: assets/logo/fletx.png
  language: en
  features:
    # - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - navigation.prune

    # - toc.integrate
    - toc.follow

    # SEARCH
    - search.suggest
    - search.highlight

    # CODE
    - code.copy
    - code.annotate
    - code.tabs
    - code.expand
    - content.code.copy
    - content.code.select

    # CONTENT ACTIONS
    - content.action.edit
    - content.action.view

  # PALETTE
  palette:
    - scheme: slate
      primary: indigo
      accent: light blue

  # FONTS
  font:
    text: Inter
    code: Chivo Mono

# Extra JS files
extra_javascript:
  - assets/javascript/msdl.v1.js
  - assets/javascript/init_kapa_widget.v2.js

# Extra CSS files
extra_css:
  - assets/stylesheets/msdl.v2.css
  - assets/stylesheets/theme.v3.css

# NAVIGATION
nav:
  # HOME
  - Home: index.md

  # GETTING STARTED
  - Getting Started:
      - Introduction: getting-started/installation.md
      - FletX CLI: getting-started/fletx-cli.md
      - Architecture: getting-started/architecture.md
      - State Management: getting-started/state-management.md
      - Controllers: getting-started/controllers.md
      - Pages (views): getting-started/pages.md
      - Routing System: getting-started/routing.md
      - Dependency Injection: getting-started/dependency-injection.md
      - Services: getting-started/services.md

  # GUIDES
  # - Guides:

  # API REFERENCE
  - API Reference: api-reference.md

  # CONTRIBUTIONG
  - Contributing: contributing.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      # Use Twemoji for emojis
      # This is the default, but explicitly specifying for clarity
      # emoji_index: !!python/name:material.extensions.emoji.twemoji
      # emoji_generator: !!python/name:material.extensions.emoji.to_svg

  #
  - abbr
  - attr_list
  - md_in_html

plugins:
  - search
  # - i18n:
  #     default_language: en
  #     languages:
  #       - locale: en
  #         name: English
  #         default: true
  #         build: true
        # - locale: fr
        #   name: Français
        #   default: false
        #   build: true

  # - macros:
      # on_error_fail: true
      # include_dir: includes

# Extra metadata
extra:
  version: 0.1.4.dev1
  description: Documentation for FletX, a lightweight yet powerful framework that brings structured reactivity and clean architecture to Flet apps. It introduces controllers, services, and routers to help you separate logic, state, and UI with ease.

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AllDotPy/FletX
      name: FletX on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/easyswitch
      name: FletX on X
